force-app/main/default/objects/Event_Handler_Route__mdt/Event_Handler_Route__mdt.object-meta.xml
<CustomObject>
    <label>Event Handler Route</label>
    <pluralLabel>Event Handler Routes</pluralLabel>
</CustomObject>

force-app/main/default/objects/Event_Handler_Route__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event_Handler_Route__mdt/fields/Handler_Api_Name__c.field-meta.xml
<CustomField>
    <fullName>Handler_Api_Name__c</fullName>
    <inlineHelpText>Apex class implementing EvtHandlerInterface</inlineHelpText>
    <label>Handler Api Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Handler_Route__mdt/fields/Handler_Type__c.field-meta.xml
<CustomField>
    <fullName>Handler_Type__c</fullName>
    <label>Handler Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apex</fullName>
                <default>true</default>
                <label>Apex</label>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EvtLog__c/EvtLog__c.object-meta.xml
<CustomObject>
    <label>EvtLog</label>
    <nameField>
        <displayFormat>Evt-{0}</displayFormat>
        <label>EvtLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EvtLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EvtLog__c/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <label>Data</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EvtLog__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <label>Error Message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/EvtLog__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EvtLog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EvtLog__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Generic_Event__e/Generic_Event__e.object-meta.xml
<CustomObject>
    <label>Generic Event</label>
    <pluralLabel>Generic Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Generic_Event__e/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <label>Data</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Generic_Event__e/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EvtDispatcher.cls
public without sharing class EvtDispatcher {
    public static void dispatchEvents(List<Generic_Event__e> eventList) {
        Map<String, List<Generic_Event__e>> eventMap = groupEventsByType(eventList);
        for (String eventType : eventMap.keySet()) {
            EvtLog__c log = new EvtLog__c(
                Type__c = eventType,
                Status__c = 'Success',
                Data__c = JSON.serializePretty(eventMap.get(eventType))
            );
            try {
                Event_Handler_Route__mdt route = Event_Handler_Route__mdt.getInstance(eventType);
                if (route != null) {
                    if (route.Active__c) {
                        if (route.Handler_Type__c == 'Apex') {
                            System.Type handlerClassType = Type.forName(route.Handler_Api_Name__c);
                            EvtHandlerInterface handler = (EvtHandlerInterface) handlerClassType.newInstance();
                            handler.execute(eventMap.get(eventType));
                        } else if (route.Handler_Type__c == 'Flow') {
                            for (Generic_Event__e eventObj : eventMap.get(eventType)) {
                                Map<String, Object> inputVariables = (Map<String, Object>) JSON.deserializeUntyped(
                                    eventObj.Data__c
                                );
                                Flow.Interview flowInterview = Flow.Interview.createInterview(
                                    route.Handler_Api_Name__c,
                                    inputVariables
                                );
                                flowInterview.start();
                            }
                        } else {
                            throw new EvtDispatchException('Invalid handler type: ' + route.Handler_Type__c);
                        }
                    } else {
                        throw new EvtDispatchException('Route inactive for event type "' + eventType + '"');
                    }
                } else {
                    throw new EvtDispatchException('Route not found for event type "' + eventType + '"');
                }
            } catch (Exception ex) {
                log.Status__c = 'Error';
                log.Error_Message__c = ex.getMessage();
                log.Stack_Trace__c = ex.getStackTraceString();
            } finally {
                insert log;
            }
        }
    }

    private static Map<String, List<Generic_Event__e>> groupEventsByType(List<Generic_Event__e> eventList) {
        Map<String, List<Generic_Event__e>> eventMap = new Map<String, List<Generic_Event__e>>();
        for (Generic_Event__e eventObj : eventList) {
            List<Generic_Event__e> evtList = eventMap.get(eventObj.Type__c);
            if (evtList == null) {
                evtList = new List<Generic_Event__e>();
                eventMap.put(eventObj.Type__c, evtList);
            }
            evtList.add(eventObj);
        }
        return eventMap;
    }

    public class EvtDispatchException extends Exception {
    }
}