force-app/main/default/objects/EvtLog__c/EvtLog__c.object-meta.xml
<CustomObject>
    <label>EvtLog</label>
    <nameField>
        <displayFormat>Evt-{0}</displayFormat>
        <label>EvtLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EvtLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EvtLog__c/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <label>Data</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EvtLog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EvtLog__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Generic_Event__e/Generic_Event__e.object-meta.xml
<CustomObject>
    <label>Generic Event</label>
    <pluralLabel>Generic Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Generic_Event__e/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <label>Data</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Generic_Event__e/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EvtDispatcherTest.cls
@IsTest
public class EvtDispatcherTest {
    @IsTest
    static void dispatchApexEvent() {
        EvtSampleHandler.SampleMessage msg = new EvtSampleHandler.SampleMessage();
        msg.body = 'Hello world!';
        List<Generic_Event__e> eventList = new List<Generic_Event__e>();
        eventList.add(new Generic_Event__e(Type__c = 'SampleApex', Data__c = JSON.serialize(msg)));

        Test.startTest();
        EvtDispatcher.dispatchEvents(eventList);
        Test.stopTest();

        List<EvtLog__c> evtLogList = [SELECT Id, Status__c FROM EvtLog__c];
        Assert.areEqual(1, evtLogList.size(), 'EvtLog not created');
        Assert.areEqual('Success', evtLogList[0].Status__c);
    }

    @IsTest
    static void dispatchFlowEvent() {
        EvtSampleHandler.SampleMessage msg = new EvtSampleHandler.SampleMessage();
        msg.body = 'Hello world!';
        List<Generic_Event__e> eventList = new List<Generic_Event__e>();
        eventList.add(new Generic_Event__e(Type__c = 'SampleFlow', Data__c = JSON.serialize(msg)));

        Test.startTest();
        EvtDispatcher.dispatchEvents(eventList);
        Test.stopTest();

        List<EvtLog__c> evtLogList = [SELECT Id, Status__c FROM EvtLog__c];
        Assert.areEqual(1, evtLogList.size(), 'EvtLog not created');
        Assert.areEqual('Success', evtLogList[0].Status__c);
    }
}