force-app/main/default/objects/EvtLog__c/EvtLog__c.object-meta.xml
<CustomObject>
    <label>EvtLog</label>
    <nameField>
        <displayFormat>Evt-{0}</displayFormat>
        <label>EvtLog Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EvtLogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EvtLog__c/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <label>Data</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/EvtLog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EvtLog__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Generic_Event__e/Generic_Event__e.object-meta.xml
<CustomObject>
    <label>Generic Event</label>
    <pluralLabel>Generic Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Generic_Event__e/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <label>Data</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Generic_Event__e/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EvtLoggerTest.cls
@IsTest
public class EvtLoggerTest {
    @IsTest
    static void testSuccessLog() {
        List<Generic_Event__e> eventList = new List<Generic_Event__e>{
            new Generic_Event__e(Type__c = 'Test', Data__c = '{"body":"hello world!"}')
        };

        Test.startTest();
        EvtLogger logger = new EvtLogger();
        logger.buildLog(eventList);
        logger.saveLogs();
        Test.stopTest();

        List<EvtLog__c> logList = [SELECT Id, Status__c FROM EvtLog__c];
        Assert.areEqual(1, logList.size());
        Assert.areEqual('Success', logList[0].Status__c);
    }

    @IsTest
    static void testErrorLog() {
        List<Generic_Event__e> eventList = new List<Generic_Event__e>{
            new Generic_Event__e(Type__c = 'Test', Data__c = '{"body":"hello world!"}')
        };

        Test.startTest();
        EvtLogger logger = new EvtLogger();
        logger.buildLog(eventList);
        try {
            throw new TestException();
        } catch (TestException ex) {
            logger.addException(ex);
        }
        logger.saveLogs();
        Test.stopTest();

        List<EvtLog__c> logList = [SELECT Id, Status__c FROM EvtLog__c];
        Assert.areEqual(1, logList.size());
        Assert.areEqual('Error', logList[0].Status__c);
    }

    private class TestException extends Exception {
    }
}