force-app/main/default/objects/Generic_Event__e/Generic_Event__e.object-meta.xml
<CustomObject>
    <label>Generic Event</label>
    <pluralLabel>Generic Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Generic_Event__e/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <label>Data</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Generic_Event__e/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EvtAbstractRecordHandlerTest.cls
@IsTest
public class EvtAbstractRecordHandlerTest {
    @IsTest
    static void testExecute() {
        Test.startTest();
        Map<String, SObject> data = new Map<String, SObject>();
        data.put('Record', new Contact(Id = '003DR00000o1SAGYA2'));
        data.put('RecordPrior', new Contact(Id = '003DR00000o1SAGYA2'));
        List<Generic_Event__e> eventList = new List<Generic_Event__e>{
            new Generic_Event__e(Type__c = 'Test', Data__c = JSON.serialize(data))
        };
        TestHandler handler = new TestHandler();
        handler.execute(eventList);
        Test.stopTest();

        Assert.isTrue(didRun);
    }

    private static Boolean didRun = false;

    private class TestHandler extends EvtAbstractRecordHandler {
        protected override void handle(EvtRecordContext ctx) {
            didRun = true;
        }
    }
}