force-app/main/default/objects/Generic_Event__e/Generic_Event__e.object-meta.xml
<CustomObject>
    <label>Generic Event</label>
    <pluralLabel>Generic Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Generic_Event__e/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <label>Data</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/EvtAbstractHandler.cls
public abstract class EvtAbstractHandler implements EvtHandlerInterface {
    public void execute(List<Generic_Event__e> eventList) {
        String rawMessageList = '';
        for (Generic_Event__e eventObj : eventList) {
            rawMessageList += eventObj.Data__c + ',';
        }
        rawMessageList = '[' + rawMessageList.removeEnd(',') + ']';
        List<Object> messageList = (List<Object>) JSON.deserialize(rawMessageList, getMessageType());
        handle(messageList);
    }
    protected abstract System.Type getMessageType();

    protected abstract void handle(List<Object> messageList);
}