force-app/main/default/objects/Generic_Event__e/Generic_Event__e.object-meta.xml
<CustomObject>
    <label>Generic Event</label>
    <pluralLabel>Generic Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Generic_Event__e/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <label>Data</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/EvtFlowRunnerTest.cls
@IsTest
public class EvtFlowRunnerTest {
    @IsTest
    static void testRun() {
        Test.startTest();
        EvtRunnerContext ctx = new EvtRunnerContext();
        ctx.handlerApiName = 'EvtSampleFlowHandler';
        ctx.eventList = new List<Generic_Event__e>();
        ctx.eventList.add(new Generic_Event__e(Data__c = '{ "body": "hello world!" }'));
        EvtFlowRunner runner = new EvtFlowRunner();
        runner.run(ctx);
        Test.stopTest();
    }
}