force-app/main/default/objects/Generic_Event__e/Generic_Event__e.object-meta.xml
<CustomObject>
    <label>Generic Event</label>
    <pluralLabel>Generic Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Generic_Event__e/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <label>Data</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/EvtRecordFlowRunner.cls
public class EvtRecordFlowRunner implements EvtRunner {
    public void run(EvtRunnerContext ctx) {
        for (Generic_Event__e eventObj : ctx.eventList) {
            EvtRecordInfo info = (EvtRecordInfo) JSON.deserialize(eventObj.Data__c, EvtRecordInfo.class);
            Map<String, SObject> inputVariables = new Map<String, SObject>();
            inputVariables.put('Record', info.Record);
            inputVariables.put('RecordPrior', info.RecordPrior);
            Flow.Interview flowInterview = Flow.Interview.createInterview(ctx.handlerApiName, inputVariables);
            flowInterview.start();
        }
    }
}