force-app/main/default/objects/Generic_Event__e/Generic_Event__e.object-meta.xml
<CustomObject>
    <label>Generic Event</label>
    <pluralLabel>Generic Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Generic_Event__e/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <label>Data</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/EvtRecordFlowRunnerTest.cls
@IsTest
public class EvtRecordFlowRunnerTest {
    @IsTest
    static void testRun() {
        Contact record = new Contact(FirstName = 'Bruce', LastName = 'Lee');
        Contact recordPrior = new Contact(FirstName = 'Bruce', LastName = 'Wayne');
        Map<String, SObject> data = new Map<String, SObject>();
        data.put('Record', record);
        data.put('RecordPrior', recordPrior);
        String jsonStr = JSON.serializePretty(data);

        Test.startTest();
        EvtRunnerContext ctx = new EvtRunnerContext();
        ctx.handlerApiName = 'EvtSampleRecordFlowHandler';
        ctx.eventList = new List<Generic_Event__e>();
        ctx.eventList.add(new Generic_Event__e(Data__c = jsonStr));
        EvtRecordFlowRunner runner = new EvtRecordFlowRunner();
        runner.run(ctx);
        Test.stopTest();
    }
}