force-app/main/default/objects/Generic_Event__e/Generic_Event__e.object-meta.xml
<CustomObject>
    <label>Generic Event</label>
    <pluralLabel>Generic Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Generic_Event__e/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <label>Data</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/EvtFlowRunner.cls
public class EvtFlowRunner implements EvtRunner {
    public void run(EvtRunnerContext ctx) {
        for (Generic_Event__e eventObj : ctx.eventList) {
            Map<String, Object> inputVariables = (Map<String, Object>) JSON.deserializeUntyped(eventObj.Data__c);
            Flow.Interview flowInterview = Flow.Interview.createInterview(ctx.handlerApiName, inputVariables);
            flowInterview.start();
        }
    }
}